name: zedsecure
description: "A professional VPN application with modern UI design"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_v2ray_client:
    path: local_packages/flutter_v2ray_client
  
  fluent_ui: ^4.11.5
  glassmorphism: ^3.0.0
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
