name: Build & Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'
          cache: true
      
      - name: Flutter Doctor
        run: flutter doctor -v
      
      - name: Install Dependencies
        run: flutter pub get
      
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/zedsecure-release-new.keystore
          echo "✅ Keystore file created successfully"
      
      - name: Create key.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "storeFile=android/app/zedsecure-release-new.keystore" > key.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> key.properties
          echo "keyAlias=$KEY_ALIAS" >> key.properties
          echo "keyPassword=$KEY_PASSWORD" >> key.properties
          echo "✅ key.properties created successfully"
      
      - name: Build APK (ARM64-v8a)
        run: flutter build apk --release --target-platform android-arm64
      
      - name: Build APK (ARMv7a)
        run: flutter build apk --release --target-platform android-arm
      
      - name: Get Version
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="1.2.0"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Rename APK Files
        run: |
          mkdir -p release-apks
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk release-apks/zedsecure-${{ steps.version.outputs.version }}-arm64-v8a.apk
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk release-apks/zedsecure-${{ steps.version.outputs.version }}-armeabi-v7a.apk
      
      - name: Upload ARM64 APK
        uses: actions/upload-artifact@v4
        with:
          name: zedsecure-arm64-v8a
          path: release-apks/zedsecure-${{ steps.version.outputs.version }}-arm64-v8a.apk
      
      - name: Upload ARMv7 APK
        uses: actions/upload-artifact@v4
        with:
          name: zedsecure-armeabi-v7a
          path: release-apks/zedsecure-${{ steps.version.outputs.version }}-armeabi-v7a.apk
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-apks/zedsecure-${{ steps.version.outputs.version }}-arm64-v8a.apk
            release-apks/zedsecure-${{ steps.version.outputs.version }}-armeabi-v7a.apk
          body: |
            ## 🚀 Zed-Secure VPN ${{ steps.version.outputs.version }}
            
            ### 📥 Downloads
            
            **Recommended**: `zedsecure-${{ steps.version.outputs.version }}-arm64-v8a.apk` (for most modern devices)
            
            - **ARM64-v8a**: For most modern Android devices (2015+) - **RECOMMENDED**
            - **ARMv7a**: For older Android devices (2012-2015)
            
            ### ✨ What's New in v1.2.0
            
            #### Major Features
            - ✨ **Light/Dark Mode**: Toggle between themes in Settings
            - ⚡ **Concurrent Ping**: Test all servers simultaneously (much faster!)
            - 💾 **Backup & Restore**: Export/import your configs as JSON
            - 📷 **QR Code Scanner**: Scan configs with camera
            - 🎨 **Improved UI**: Better config cards, click-to-select, 2-line names
            
            #### Enhancements
            - 🎯 **Individual Ping Button**: Test specific servers on demand
            - 🗑️ **Delete Dead Configs**: Remove failed servers with one tap
            - 📋 **Three-Dot Menu**: Copy config, show QR, delete per config
            - 🔧 **Better About Section**: Developer info with GitHub link
            - 📦 **Updated Dependencies**: Flutter 3.35.5, Dart 3.9.2, Kotlin 2.2.20
            
            #### Protocol Support
            - 🚀 **XHTTP Transport** (new in Xray 1.25.3)
            - 🚀 **HTTPUpgrade Transport** (new in Xray 1.25.3)
            
            #### Bug Fixes
            - 🐛 Fixed config name display (now shows 2 lines)
            - 🐛 Fixed UI overflow in header icons
            - 🐛 Fixed card size after ping
            - 🐛 Removed select button, click card to select
            - 🐛 Fixed notification persistence issue
            
            ### 📝 Installation
            
            1. Download the appropriate APK for your device
            2. Enable "Install from Unknown Sources" in Android settings
            3. Install the APK
            4. Grant VPN and notification permissions
            5. Enjoy secure browsing!
            
            ### ⚠️ Google Play Protect Warning
            
            If you see "App scan recommended" or similar warnings, this is normal for apps not distributed through Google Play Store. The app is **open source** and safe. You can:
            - Click "Install Anyway" or "Install Without Scanning"
            - Or review the source code yourself: https://github.com/CluvexStudio/ZedSecure
            
            ### 🔐 Security
            
            - ✅ Open Source - Fully transparent code
            - ✅ No data collection or telemetry
            - ✅ Encrypted local storage
            - ✅ GPL-3.0 Licensed
            
            ### 📖 Documentation
            
            - [README](https://github.com/CluvexStudio/ZedSecure/blob/main/README.md)
            - [Build Instructions](https://github.com/CluvexStudio/ZedSecure#-build-from-source)
            - [Contributing Guide](https://github.com/CluvexStudio/ZedSecure/blob/main/CONTRIBUTING.md)
            
            ### 🙏 Support
            
            If you find this project helpful, please ⭐ star the repository!
            
            **Telegram Channel**: https://t.me/CluvexStudio
            
            ---
            
            **Developed by CluvexStudio**  
            *Building open-source tools for digital freedom and privacy*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
